Repository ComputerScienceHouse/Constitution, pull requests merged in 2019-02, with the labels that each got.

#139 Remove Freshman Project
  articles.tex
  bylaws.tex
Labels: Ballot Passed

#144 Remove unneccessary enumeration from Introductory Packet requirements
  bylaws.tex
Labels: Formatting Error

#141 Secretary Responsibilities Update
  articles.tex
Labels: Ballot Pending, Proposal
